/** Re-export shared catalog — single source of truth in @first2apply/core */
export {
  AI_PROVIDER_CONFIG,
  AI_TASKS,
  LLM_MAX_HTML_CHARS,
  LLM_MAX_JD_FILTER_DESCRIPTION_CHARS,
  PROVIDER_NAMES,
  getApiModelId,
  getDefaultTaskConfig,
  getModelConfig,
  getProviderDisplayName,
  getProviderModels,
  getProviderNames,
  getStoredProviderKeys,
  getTaskMeta,
  isProviderName,
  resolveTaskAiConfig,
  validateApiKeyFormat,
  type AdvancedMatchingAiFields,
  type AiTaskConfig,
  type AiTaskId,
  type AiTaskMeta,
  type ModelConfig,
  type ProviderConfig,
  type ProviderName,
} from '@first2apply/core';
