import { ENV } from './env';

import { DbSchema, getExceptionMessage } from '@first2apply/core';
import { createClient } from '@supabase/supabase-js';
import { BrowserWindow, Notification, app, dialog, nativeTheme, safeStorage, shell } from 'electron';
import Storage from 'electron-store';
import fs from 'fs';
import path from 'path';

import { AmplitudeAnalyticsClient } from './server/amplitude';
import { F2aAutoUpdater } from './server/autoUpdater';
import { promiseAllSequence } from './server/helpers';
import { HtmlDownloader } from './server/htmlDownloader';
import { JobScanner } from './server/jobScanner';
import { logger } from './server/logger';
import { OverlayBrowserView } from './server/overlayBrowserView';
import { initRendererIpcApi } from './server/rendererIpcApi';
import { F2aSupabaseApi } from './server/supabaseApi';
import { TrayMenu } from './server/trayMenu';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Suppress Electron/macOS deprecation warnings
process.removeAllListeners('warning');
process.on('warning', (warning) => {
  // Suppress punycode deprecation warnings
  if (warning.name === 'DeprecationWarning' && warning.message.includes('punycode')) {
    return;
  }
  // Log other warnings normally
  console.warn(warning.name, warning.message);
});

// Suppress stderr output for task_policy_set errors on macOS (these come from Electron Helper processes)
const originalStderrWrite = process.stderr.write.bind(process.stderr);
// Type assertion needed due to overloaded write method signatures
process.stderr.write = function (chunk: string | Uint8Array, encoding?: BufferEncoding, callback?: (error?: Error | null) => void): boolean {
  const message = typeof chunk === 'string' ? chunk : chunk.toString();
  // Suppress task_policy_set and Continuity Camera warnings
  if (
    message.includes('task_policy_set') ||
    message.includes('NSCameraUseContinuityCameraDeviceType') ||
    message.includes('AVCaptureDeviceTypeExternal') ||
    message.includes('AVCaptureDeviceTypeContinuityCamera')
  ) {
    return true;
  }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return (originalStderrWrite as any)(chunk, encoding, callback);
} as typeof process.stderr.write;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const APP_PROTOCOL = 'first2fetch';
let appIsRunning = false;
let isQuitting = false; // Flag to prevent multiple quit calls
const storage = new Storage<{
  width: number;
  height: number;
}>({ defaults: { width: 1024, height: 800 } });

// register the custom protocol
if (process.defaultApp) {
  if (process.argv.length >= 2) {
    app.setAsDefaultProtocolClient(APP_PROTOCOL, process.execPath, [path.resolve(process.argv[1])]);
  }
} else {
  app.setAsDefaultProtocolClient(APP_PROTOCOL);
}

let mainWindow: BrowserWindow | null = null;
let trayIconNotificationShown = false;
const createMainWindow = () => {
  // Create the browser window.
  if (mainWindow) return;
  const theme = nativeTheme.shouldUseDarkColors ? 'dark' : 'light';
  mainWindow = new BrowserWindow({
    width: storage.get('width'),
    height: storage.get('height'),
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      additionalArguments: [theme],
      partition: `persist:scraper`,
    },
    autoHideMenuBar: true,
  });

  // Suppress DevTools protocol warnings
  mainWindow.webContents.on('console-message', (event, _level, message, _line, _sourceId) => {
    // Suppress Autofill protocol warnings
    if (
      message.includes('Autofill.enable') ||
      message.includes('Autofill.setAddresses') ||
      message.includes("wasn't found")
    ) {
      event.preventDefault();
      return;
    }
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  if (ENV.nodeEnv === 'development') {
    // Open the DevTools.
    mainWindow.webContents.openDevTools();
  }

  mainWindow.on('close', (event) => {
    event.preventDefault();
    onHideToSystemTray();
  });

  // open all external links in the default browser
  mainWindow.webContents.on('will-navigate', (event, url) => {
    if (url.startsWith('http') && !url.includes('main_window')) {
      event.preventDefault();
      shell.openExternal(url);
    }
  });

  return mainWindow;
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  bootstrap();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  app.quit();
});

// do not close all windows when the app is quit on macOS, instead hide the main window
app.on('before-quit', (event) => {
  // Allow force quit to proceed without preventing default
  if (isQuitting) {
    return;
  }
  if (appIsRunning) {
    event.preventDefault();
    onHideToSystemTray();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  onActivate();
});

function onActivate() {
  if (!mainWindow?.isVisible()) {
    // show the dock icon on macOS and show the taskbar icon on Windows
    if (process.platform === 'darwin') {
      app.dock.show();
    } else if (process.platform === 'win32') {
      mainWindow?.setSkipTaskbar(false);
    }

    mainWindow?.show();
  }

  if (mainWindow?.isMinimized()) {
    mainWindow?.restore();
  }

  mainWindow?.focus();
}
function onHideToSystemTray() {
  mainWindow?.hide();

  // hide the dock icon on macOS and hide the taskbar icon on Windows
  if (process.platform === 'darwin') {
    app.dock.hide();
  } else if (process.platform === 'win32') {
    mainWindow?.setSkipTaskbar(true);
  }

  // dirty hack to fix navigating to the right tab in home page
  // when closing we navigate to help page
  mainWindow?.webContents.send('navigate', { path: '/help' });

  // send notification to inform the user that the app is still running
  if (!trayIconNotificationShown) {
    trayIconNotificationShown = true;
    const notification = new Notification({
      title: 'See you soon!',
      body: 'First 2 Apply is still checking for new jobs in the background. Click the paper airplane icon in your system tray to open the app.',
    });
    notification.show();
  }
}

// globals
const analytics = new AmplitudeAnalyticsClient();
const autoUpdater = new F2aAutoUpdater(logger, quit, analytics);
const supabase = createClient<DbSchema>(ENV.supabase.url, ENV.supabase.key, {
  auth: {
    // Disable automatic persistence since we handle it manually in Electron
    autoRefreshToken: true,
    persistSession: false, // We handle session persistence manually with encrypted storage
    detectSessionInUrl: false, // Not relevant in Electron
  },
});
const supabaseApi = new F2aSupabaseApi(supabase, ENV.supabase.key);
const htmlDownloaders = [
  new HtmlDownloader({
    logger,
    numInstances: 2,
    incognitoMode: false,
  }),
  new HtmlDownloader({
    logger,
    numInstances: 1,
    incognitoMode: true,
  }),
];
let jobScanner: JobScanner | undefined;
let trayMenu: TrayMenu | undefined;
const overlayBrowserView = new OverlayBrowserView();

function navigate({ path }: { path: string }) {
  logger.info(`sending nav event to ${path}`);
  mainWindow?.webContents.send('navigate', { path });
  onActivate(); // make sure the window is visible
}

/**
 * Method used to force quit the app immediately.
 */
async function forceQuit() {
  // Prevent multiple simultaneous quit calls
  if (isQuitting) {
    logger.info(`force quit already in progress, skipping...`);
    return;
  }
  isQuitting = true;
  appIsRunning = false;

  logger.info(`force quitting...`);

  // Close main window immediately to prevent further interactions
  if (mainWindow && !mainWindow.isDestroyed()) {
    try {
      mainWindow.removeAllListeners('close');
      mainWindow.destroy();
    } catch (error) {
      // Ignore errors
    }
  }

  // Perform cleanup in parallel with timeout
  const cleanupPromises: Promise<void>[] = [];

  // Close job scanner
  cleanupPromises.push(
    (async () => {
      try {
        jobScanner?.close();
        logger.info(`closed job scanner`);
      } catch (error) {
        logger.debug(`error closing job scanner: ${getExceptionMessage(error)}`);
      }
    })(),
  );

  // Close HTML downloaders (with individual error handling)
  cleanupPromises.push(
    promiseAllSequence(htmlDownloaders, async (htmlDownloader) => {
      try {
        await htmlDownloader.close();
      } catch (error) {
        // Ignore errors when closing - windows may already be destroyed
        logger.debug(`error closing html downloader instance: ${getExceptionMessage(error)}`);
      }
    }).then(() => {
      logger.info(`closed html downloader`);
    }),
  );

  // Close tray menu
  cleanupPromises.push(
    (async () => {
      try {
        trayMenu?.close();
        logger.info(`closed tray menu`);
      } catch (error) {
        logger.debug(`error closing tray menu: ${getExceptionMessage(error)}`);
      }
    })(),
  );

  // Stop auto updater
  cleanupPromises.push(
    (async () => {
      try {
        autoUpdater.stop();
        logger.info(`stopped auto updater`);
      } catch (error) {
        logger.debug(`error stopping auto updater: ${getExceptionMessage(error)}`);
      }
    })(),
  );

  // Track and flush analytics
  cleanupPromises.push(
    (async () => {
      try {
        analytics.trackEvent('app_force_quit');
        analytics.flush();
      } catch (error) {
        logger.debug(`error flushing analytics: ${getExceptionMessage(error)}`);
      }
    })(),
  );

  // Wait for cleanup with timeout (max 2 seconds)
  try {
    await Promise.race([
      Promise.all(cleanupPromises),
      new Promise((resolve) => setTimeout(resolve, 2000)),
    ]);
  } catch (error) {
    logger.debug(`error during cleanup: ${getExceptionMessage(error)}`);
  }

  // Flush logger (non-blocking)
  try {
    logger.flush();
  } catch (error) {
    // Ignore logger flush errors
  }

  logger.info(`force quit complete, exiting...`);

  // Use app.exit() for immediate exit (bypasses before-quit handlers)
  // This will terminate the process immediately
  setImmediate(() => {
    app.exit(0);
  });
}

async function handleDeepLink(url: string) {
  try {
    if (!url.startsWith(APP_PROTOCOL)) return;

    onActivate();
    const path = url.replace(`${APP_PROTOCOL}:/`, '');

    // handle password reset links, parse hash and extract supabase tokens
    if (path.startsWith('/reset-password')) {
      const hash = path.replace(/\/reset-password\/?#/i, '');
      const params = new URLSearchParams(hash);
      const allHashParams = Object.fromEntries(params.entries());

      // @ts-expect-error -- supabase types ---
      const { error } = await supabase.auth.setSession(allHashParams);
      if (error) throw error;
    }

    navigate({ path });
  } catch (error) {
    logger.error(getExceptionMessage(error));
    dialog.showErrorBox('Error', getExceptionMessage(error, true));
  }
}

/**
 * Bootstrap probe service.
 */
async function bootstrap() {
  try {
    // do not allow multiple instances on Windows
    const gotTheLock = app.requestSingleInstanceLock();
    if (!gotTheLock) {
      app.quit();
      return;
    }

    if (!ENV.appBundleId) throw new Error(`missing APP_BUNDLE_ID`);
    if (process.platform === 'win32') {
      app.setAppUserModelId(ENV.appBundleId);
    }

    // track the app start event
    analytics.trackEvent('app_start');

    // start auto-updater
    autoUpdater.start();

    // init the HTML downloader
    htmlDownloaders.forEach((htmlDownloader) => htmlDownloader.init());
    const [normalHtmlDownloader, incognitoHtmlDownloader] = htmlDownloaders;

    // init the job scanner
    jobScanner = new JobScanner({
      logger,
      supabaseApi,
      normalHtmlDownloader,
      incognitoHtmlDownloader,
      onNavigate: navigate,
      analytics,
    });

    // init the renderer IPC API
    initRendererIpcApi({ supabaseApi, jobScanner, autoUpdater, overlayBrowserView, nodeEnv: ENV.nodeEnv, analytics, onForceQuit: forceQuit });

    // init the tray menu
    trayMenu = new TrayMenu({ logger, onQuit: quit, onNavigate: navigate });

    const userDataPath = app.getPath('userData');
    const sessionPath = path.join(userDataPath, `${ENV.nodeEnv}-encrypted-session.json`);

    // manual logout for testing
    // fs.unlinkSync(sessionPath);

    // save the session to disk when it changes
    supabase.auth.onAuthStateChange(async (event, session) => {
      try {
        logger.info(`auth state change: ${event}`);
        logger.addMeta('user_id', session?.user?.id || 'none');

        if (session?.user?.id) {
          // set the user id for logging and analytics
          analytics.setUserId(session.user.id);
        }

        // clear the session from disk if it's being removed
        if (event === 'SIGNED_OUT') {
          logger.info(`removing session from disk`);
          fs.unlinkSync(sessionPath);
        } else if (event === 'SIGNED_IN' || event === 'TOKEN_REFRESHED' || event === 'PASSWORD_RECOVERY') {
          logger.info(`saving new session to disk`);
          if (safeStorage.isEncryptionAvailable()) {
            const encryptedSession = safeStorage.encryptString(JSON.stringify(session));
            fs.writeFileSync(sessionPath, encryptedSession.toString('base64'), 'utf-8');
          } else {
            logger.error(`encryption is not available, cannot save plain session to disk`);
          }
        }
      } catch (error) {
        logger.error(getExceptionMessage(error));
      }
    });

    // load the session from disk if it exists
    if (fs.existsSync(sessionPath)) {
      const encryptedSession = fs.readFileSync(sessionPath, 'utf-8');
      const plaintextSession = safeStorage.decryptString(Buffer.from(encryptedSession, 'base64'));
      const session = JSON.parse(plaintextSession);
      logger.info(`finished loading session from disk`);
      const { error } = await supabase.auth.setSession(session);
      if (error) throw error;

      // perform an initial scan
      jobScanner.scanAllLinks().catch((error) => {
        logger.error(getExceptionMessage(error));
      });
    } else {
      logger.info(`no session found on disk`);
    }
  } catch (error) {
    logger.error(getExceptionMessage(error));
  }

  // create the main window after everything is setup
  const mainWindow = createMainWindow();
  overlayBrowserView.setMainWindow(mainWindow);

  // handle deep links on macOS and linux
  app.on('open-url', (event, url) => {
    event.preventDefault();
    handleDeepLink(url);
  });

  // handle deep links on Windows
  app.on('second-instance', (event, commandLine) => {
    handleDeepLink(commandLine[commandLine.length - 1]);
  });

  appIsRunning = true;
}

/**
 * Method used to quit the app.
 */
async function quit() {
  try {
    logger.info(`quitting...`);
    appIsRunning = false;

    jobScanner?.close();
    logger.info(`closed job scanner`);

    await promiseAllSequence(htmlDownloaders, (htmlDownloader) => htmlDownloader.close());
    logger.info(`closed html downloader`);

    trayMenu?.close();
    logger.info(`closed tray menu`);

    autoUpdater.stop();
    logger.info(`stopped auto updater`);

    storage.set('width', mainWindow?.getSize()[0] || 1024);
    storage.set('height', mainWindow?.getSize()[1] || 800);

    mainWindow?.removeAllListeners();
    logger.info(`removed all main window listeners`);

    mainWindow?.close();
    logger.info(`closed main window`);

    analytics.trackEvent('app_quit');

    analytics.flush();
    logger.flush();
  } catch (error) {
    logger.error(getExceptionMessage(error));
    process.exit(-1); // force quit
  }
}
