-- Create core tables: sites, links, jobs, reviews, html_dumps, notes, profiles
-- This migration establishes the foundational schema for the application

-- Create sites table (no dependencies)
create table if not exists public.sites (
  id bigint generated by default as identity,
  name text not null,
  urls text[] not null,
  created_at timestamp with time zone not null default now(),
  "queryParamsToRemove" text[] null,
  logo_url text not null,
  blacklisted_paths text[] not null default '{/}'::text[],
  provider text not null,
  deprecated boolean not null default false,
  incognito_support boolean not null default false,
  constraint sites_pkey primary key (id)
) tablespace pg_default;

-- Create Job Status enum
do $$
begin
  if not exists (select 1 from pg_type where typname = 'Job Status') then
    create type public."Job Status" as enum ('new', 'applied', 'archived', 'processing', 'excluded_by_advanced_matching');
  end if;
end $$;

-- Create links table (depends on sites)
create table if not exists public.links (
  id bigint generated by default as identity,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid(),
  url text not null,
  title text not null,
  site_id bigint not null,
  scrape_failure_count integer not null default 0,
  last_scraped_at timestamp with time zone not null default (now() at time zone 'utc'::text),
  scrape_failure_email_sent boolean not null default false,
  constraint links_pkey primary key (id),
  constraint links_site_id_fkey foreign key (site_id) references sites (id) on update restrict on delete restrict,
  constraint links_user_id_fkey foreign key (user_id) references auth.users (id) on delete restrict
) tablespace pg_default;

-- Create jobs table (depends on sites and links)
create table if not exists public.jobs (
  id bigint generated by default as identity,
  user_id uuid not null default auth.uid(),
  "externalId" text not null,
  "externalUrl" text not null,
  "siteId" bigint not null,
  title text not null,
  "companyName" text not null,
  "companyLogo" text null,
  location text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  salary text null,
  tags text[] not null default '{}'::text[],
  "jobType" text null,
  status public."Job Status" not null default 'new'::"Job Status",
  description text null,
  labels text[] not null default '{}'::text[],
  link_id bigint null,
  exclude_reason text null,
  constraint jobs_pkey primary key (id),
  constraint jobs_user_id_externalid_key unique (user_id, "externalId"),
  constraint jobs_user_id_fkey foreign key (user_id) references auth.users (id) on delete restrict,
  constraint jobs_siteid_fkey foreign key ("siteId") references sites (id) on update restrict on delete restrict,
  constraint public_jobs_link_id_fkey foreign key (link_id) references links (id) on update cascade on delete set null
) tablespace pg_default;

-- Create index for jobs table (used for pagination and filtering)
create index if not exists jobs_user_id_updated_at_id_status_idx on public.jobs (user_id, updated_at desc, id desc, status);

-- Create reviews table
create table if not exists public.reviews (
  id bigint generated by default as identity,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid(),
  title text not null,
  description text null,
  rating integer not null,
  constraint reviews_pkey primary key (id),
  constraint reviews_user_id_fkey foreign key (user_id) references auth.users (id) on delete restrict,
  constraint unique_user_review unique (user_id)
) tablespace pg_default;

-- Create html_dumps table
create table if not exists public.html_dumps (
  id bigint generated by default as identity,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid(),
  url text not null,
  html text not null,
  constraint html_dumps_pkey primary key (id)
) tablespace pg_default;

-- Create notes table (depends on jobs)
create table if not exists public.notes (
  id bigint generated by default as identity,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid(),
  text text not null,
  files text[] not null default '{}'::text[],
  job_id bigint not null,
  constraint notes_pkey primary key (id),
  constraint notes_user_id_fkey foreign key (user_id) references auth.users (id) on update cascade on delete cascade,
  constraint notes_job_id_fkey foreign key (job_id) references jobs (id) on update cascade on delete cascade
) tablespace pg_default;

-- Create profiles table
create table if not exists public.profiles (
  id bigint generated by default as identity,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid(),
  stripe_customer_id text null,
  stripe_subscription_id text null,
  subscription_end_date timestamp without time zone not null default (now() + interval '10 years'),
  subscription_tier text not null default 'pro'::text,
  is_trial boolean not null default false,
  constraint profiles_pkey primary key (id),
  constraint profiles_user_id_key unique (user_id),
  constraint profiles_user_id_fkey foreign key (user_id) references auth.users (id) on delete restrict
) tablespace pg_default;

