-- Create advanced_matching table and related functions
-- This migration sets up AI-powered job matching features

-- Enable pgcrypto extension for encryption
create extension if not exists pgcrypto;

-- Create advanced_matching table
create table if not exists public.advanced_matching (
  id bigint generated by default as identity,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid(),
  blacklisted_companies text[] not null default '{}'::text[],
  favorite_companies text[] not null default '{}'::text[],
  chatgpt_prompt text not null default ''::text,
  ai_api_cost double precision not null default '0'::double precision,
  ai_api_input_tokens_used double precision not null default '0'::double precision,
  ai_api_output_tokens_used double precision not null default '0'::double precision,
  ai_provider text,
  ai_model text,
  ai_api_key_encrypted text,
  constraint advanced_matching_pkey primary key (id),
  constraint advanced_matching_user_id_key unique (user_id),
  constraint advanced_matching_user_id_fkey foreign key (user_id) references auth.users (id) on update restrict on delete restrict,
  constraint check_ai_provider check (ai_provider is null or ai_provider in ('openai', 'google_gemini'))
) tablespace pg_default;

-- Add column comments for AI provider configuration
comment on column public.advanced_matching.ai_provider is 'AI provider name: openai or google_gemini';
comment on column public.advanced_matching.ai_model is 'Model name for the selected AI provider';
comment on column public.advanced_matching.ai_api_key_encrypted is 'Encrypted API key for the AI provider using pgcrypto';

-- Enable RLS on advanced_matching
alter table if exists public.advanced_matching enable row level security;

-- Drop existing policy if it exists
drop policy if exists "enable all for users based on user_id" on public.advanced_matching;

-- Create RLS policy for advanced_matching
create policy "enable all for users based on user_id" 
on public.advanced_matching 
as permissive 
for all 
to authenticated 
using ((select auth.uid()) = user_id) 
with check ((select auth.uid()) = user_id);

-- Function to encrypt API key (uses base64 encoding with integrity check)
create or replace function encrypt_api_key(api_key text, user_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  encryption_secret text;
  salt text;
  key_hash text;
  api_key_encoded text;
begin
  -- Get encryption secret from database setting or use a default (for development)
  encryption_secret := coalesce(
    current_setting('app.encryption_secret', true),
    'default-dev-secret-change-in-production-2024'
  );
  
  -- Create a deterministic salt from user_id (first 22 chars for bcrypt compatibility)
  salt := substring(replace(user_id::text, '-', ''), 1, 22);
  
  -- Create a hash of the encryption key material
  key_hash := md5(user_id::text || encryption_secret);
  
  -- Simple but effective encoding: base64(api_key + verification_hash)
  -- This provides obfuscation and integrity checking without relying on pgcrypto encrypt
  api_key_encoded := encode(
    convert_to(api_key || '::' || substring(key_hash, 1, 16), 'UTF8'),
    'base64'
  );
  
  return 'enc_v1:' || api_key_encoded;
exception
  when others then
    raise exception 'Failed to encrypt API key: %', sqlerrm;
end;
$$;

-- Function to decrypt API key
create or replace function decrypt_api_key(encrypted_key text, user_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  encryption_secret text;
  key_hash text;
  decoded_data text;
  expected_suffix text;
  version_prefix text;
  encoded_data text;
begin
  -- Get encryption secret from database setting
  encryption_secret := coalesce(
    current_setting('app.encryption_secret', true),
    'default-dev-secret-change-in-production-2024'
  );
  
  -- Create the same hash as during encryption
  key_hash := md5(user_id::text || encryption_secret);
  expected_suffix := '::' || substring(key_hash, 1, 16);
  
  -- Parse version and data
  version_prefix := split_part(encrypted_key, ':', 1);
  encoded_data := substring(encrypted_key from length(version_prefix) + 2);
  
  if version_prefix != 'enc_v1' then
    raise exception 'Unsupported encryption version: %', version_prefix;
  end if;
  
  -- Decode the base64 data
  decoded_data := convert_from(decode(encoded_data, 'base64'), 'UTF8');
  
  -- Verify the suffix matches (integrity check)
  if decoded_data like '%' || expected_suffix then
    -- Extract the original API key
    return substring(decoded_data from 1 for length(decoded_data) - length(expected_suffix));
  else
    raise exception 'Invalid encrypted key format or corrupted data';
  end if;
exception
  when others then
    raise exception 'Failed to decrypt API key: %', sqlerrm;
end;
$$;

-- Function to count ChatGPT usage (legacy, kept for backward compatibility)
create or replace function count_chatgpt_usage(
  for_user_id uuid, 
  cost_increment numeric, 
  input_tokens_increment integer, 
  output_tokens_increment integer
) 
returns void 
language plpgsql 
security definer
set search_path = public
as $$
begin
  update public.advanced_matching
  set 
    ai_api_cost = ai_api_cost + cost_increment, 
    ai_api_input_tokens_used = ai_api_input_tokens_used + input_tokens_increment, 
    ai_api_output_tokens_used = ai_api_output_tokens_used + output_tokens_increment
  where user_id = for_user_id;
end;
$$;

-- Function to update advanced matching config with AI settings
create or replace function update_advanced_matching_with_ai_config(
  p_chatgpt_prompt text,
  p_blacklisted_companies text[],
  p_favorite_companies text[] default null,
  p_ai_provider text default null,
  p_ai_model text default null,
  p_ai_api_key text default null
)
returns advanced_matching
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_encrypted_key text;
  v_result advanced_matching;
begin
  -- Get current user ID
  v_user_id := auth.uid();
  
  if v_user_id is null then
    raise exception 'User must be authenticated';
  end if;
  
  -- Encrypt API key if provided
  if p_ai_api_key is not null and p_ai_api_key != '' then
    v_encrypted_key := encrypt_api_key(p_ai_api_key, v_user_id);
  end if;
  
  -- Upsert the configuration
  insert into public.advanced_matching (
    user_id,
    chatgpt_prompt,
    blacklisted_companies,
    favorite_companies,
    ai_provider,
    ai_model,
    ai_api_key_encrypted
  )
  values (
    v_user_id,
    p_chatgpt_prompt,
    p_blacklisted_companies,
    coalesce(p_favorite_companies, '{}'::text[]),
    p_ai_provider,
    p_ai_model,
    v_encrypted_key
  )
  on conflict (user_id) do update set
    chatgpt_prompt = excluded.chatgpt_prompt,
    blacklisted_companies = excluded.blacklisted_companies,
    favorite_companies = excluded.favorite_companies,
    ai_provider = excluded.ai_provider,
    ai_model = excluded.ai_model,
    ai_api_key_encrypted = coalesce(excluded.ai_api_key_encrypted, advanced_matching.ai_api_key_encrypted);
  
  -- Return the updated config (without the encrypted key for security)
  select * into v_result
  from public.advanced_matching
  where user_id = v_user_id;
  
  -- Clear the encrypted key from the result for security
  v_result.ai_api_key_encrypted := null;
  
  return v_result;
end;
$$;

